image:
  repository: trialq2a49v.jfrog.io/your-hello-world-repo/hello-world
  tag: latest
  pullPolicy: IfNotPresent
  pullSecret: regcred   # ✅ match the expected single string

service:
  type: LoadBalancer
  port: 80

global:
  security:
    allowInsecureImages: true



