image:
  registry: trialq2a49v.jfrog.io
  repository: your-hello-world-repo/hello-world
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

global:
  security:
    allowInsecureImages: true

imagePullSecrets:
  - name: regcred

