apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  remoteWrite:
    - url: "https://your-remote-prometheus.com/api/v1/write"
      basicAuth:
        username:
          name: prometheus-remote-secret
          key: username
        password:
          name: prometheus-remote-secret
          key: password
  resources:
    requests:
      memory: 400Mi

