prometheus:
  enabled: true
  prometheusSpec:
    serviceAccountName: prometheus-k8s
    remoteWrite:
      - url: "https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push"
        basicAuth:
          username:
            name: prometheus-remote-write-auth
            key: username
          password:
            name: prometheus-remote-write-auth
            key: password
    resources:
      requests:
        memory: 400Mi
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

kubeStateMetrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespaceSelector:
      any: true
      
alertmanager:
  enabled: true

