replicaCount: 1

image:
  repository: trialq2a49v.jfrog.io/your-hello-world-repo/hello-world
  tag: latest
  pullPolicy: IfNotPresent
  pullSecret: jfrog-secret

ingress:
  enabled: false

service:
  type: LoadBalancer
  port: 8082
  targetPort: 8082
  # Add a name for this port (important for ServiceMonitor)
  name: http

# 👇 Enables Prometheus remoteWrite and ServiceMonitor
prometheus:
  prometheusSpec:
    remoteWrite:
      - url: "https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push"
        basicAuth:
          username:
            name: prometheus-remote-write-auth
            key: username
          password:
            name: prometheus-remote-write-auth
            key: password

  monitor:
    enabled: true # Match this to your Prometheus Operator release name (default: "prometheus")
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    interval: 15s
    scrapeTimeout: 10s
    path: /metrics
    port: http  # Matches `service.name` above

defaultRules:
  create: true

kubeStateMetrics:
  metricLabelsAllowlist:
    - pods=[*]
